# Домашнее задание "Линейная алгебра. Матрицы".

## Уровень 0:


### Задание 1

 - Создайте матрицу 3 на 3, заполненную числами от 1 до 9
 - Прибавьте к ней матрицу с единицами на диагонале
 - Умножьте полученную матрицу на вектор (1, 2, 3)
 - Вычислить транспонированную матрицу $A^T$ от полученной в результате прибавления матрицы
 - Посчитайте обратную матрицу к полученной в результате прибавления матрице


In [3]:
### YOUR CODE HERE

import numpy as np

a1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
a2 = np.eye((3))
a2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
a3 = a1+a2
a3

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [9]:
a4 = np.array([1,2,3])
a4

array([1, 2, 3])

In [21]:
a5 = a3*a4

In [22]:
# np.dot(a3, a4)
# a5 = a3@a4
# a5

In [27]:
a5.T
a6 = np.transpose(a5)
a6

array([[ 2.,  4.,  7.],
       [ 4., 12., 16.],
       [ 9., 18., 30.]])

In [28]:
# определитель матрицы
np.linalg.det(a6)

-12.000000000000005

In [29]:
# ранг матрицы
np.linalg.matrix_rank(a6)

3

In [32]:
a7 = np.linalg.inv(a6)
a7

array([[-6.00000000e+00, -5.00000000e-01,  1.66666667e+00],
       [-2.00000000e+00,  2.50000000e-01,  3.33333333e-01],
       [ 3.00000000e+00, -1.66533454e-16, -6.66666667e-01]])

In [33]:
a7@a6

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 1.77635684e-15],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

## Уровень 1:

### Задание 2

Найдите собственные значения и собственные вектора матрицы:
```
m = np.array([[2, 2],
              [1, 3]])
print(m)
```



In [36]:
### YOUR CODE HERE
m = np.array([[2, 2],
              [1, 3]])
m

array([[2, 2],
       [1, 3]])

In [37]:
# собственные значения
np.linalg.eigvals(m)

array([1., 4.])

In [39]:
# собственный вектор
np.linalg.eig(m)

(array([1., 4.]),
 array([[-0.89442719, -0.70710678],
        [ 0.4472136 , -0.70710678]]))

In [40]:
res = np.linalg.eig(m)

In [43]:
res2 = res[1]
res2

array([[-0.89442719, -0.70710678],
       [ 0.4472136 , -0.70710678]])

In [44]:
res3 = res2.T
res3

array([[-0.89442719,  0.4472136 ],
       [-0.70710678, -0.70710678]])

In [49]:
res3[0]/0.4472136

array([-1.99999998,  0.99999999])

In [50]:
res3[1]/-0.70710678

array([1., 1.])

### Задание 3


Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2! 

In [ ]:
### YOUR CODE HERE

In [51]:
m2 = np.array([[2,3], [1,2]])
m2

array([[2, 3],
       [1, 2]])

In [52]:
np.linalg.det(m2)

1.0